language: node_js
node_js: lts/*
before_install:
  - npm install
cache:
  directories:
    - "node_modules"
install: true
script: echo "script"
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
