language: node_js
node_js: lts/*
before_install:
  - npm install -g firebase-tools
  - npm install
  —  firebase deploy  — project react-my-burger-3f8c2 — token $FIREBASE_TOKEN
cache:
  directories:
    - "node_modules"
install: true
script: echo "script"
