language: node_js
node_js: lts/*
before_install:
  - npm install -g firebase-tools
  - npm install
cache:
  directories:
    - "node_modules"
install: true
script: echo "script"
after_success:
  —  firebase deploy  — project react-my-burger-3f8c2 — token 1/yIdLE_Xq_BOau-tfMuiZHVGs7PSw3KeOqO79fToQlnQ
