
language: node_js
node_js:
 — “7”
script:
 — echo “Deploy!!”
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — project react-my-burger-3f8c2 — token AIzaSyCDxcPI23T0KVaW2zqGzKXh_mQkO-HC_08.